version: '3.4'

services:
  db:
    image: postgres
    ports:
      - 54321:5432
    networks:
      - backend
    environment:
        POSTGRES_PASSWORD: "InsideContainer2022"

  app:
    image: dotnetweb
    depends_on:
      - db
    ports:
      - 5000:80
    networks:
      - frontend
      - backend
    environment:
      DATABASE_URL: "postgres://postgres:InsideContainer2022@db:5432"


networks:
  frontend:
  backend:
