version: '3.4'

services:
  db:
    image: postgres
    ports:
      - 54321:5432
    networks:
      - backend
    environment:
        POSTGRES_PASSWORD: "InsideContainer2022"

  app:
    image: zaazp/dotnetweb
    depends_on:
      - db
    ports:
      - 5000:80
    networks:
      - frontend
      - backend
    environment:
        DBCONN: "Server=db;User Id=sa;Password=InsideContainer2022"

networks:
  frontend:
  backend:
