version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 54321:1433
    networks:
      - frontend
    environment:
        SA_PASSWORD: "InsideContainer2022"
        ACCEPT_EULA: "Y"

  app:
    image: zaazp/dotnetweb
    depends_on:
      - db
    ports:
      - 5000:80
    networks:
      - frontend
      - backend
    environment:
        DBCONN: "Server=db;User Id=sa;Password=InsideContainer2022"

networks:
  frontend:
  backend:
