// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_web.Models;

namespace dotnetweb.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    [Migration("20220330233421_Seed3Orders")]
    partial class Seed3Orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnet_web.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .HasMaxLength(60);

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new { Id = 1, BirthDate = new DateTime(1970, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified), Inn = "140123456789", Name = "Поликарп Петров", PhoneNumber = "+79245551122" },
                        new { Id = 2, BirthDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "nokia@bell-labs.com", Inn = "1234567890", Name = "Юникс Мультиксович Линукс", PhoneNumber = "+14151234567" },
                        new { Id = 3, BirthDate = new DateTime(1854, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "sherlock@holmes.co.uk", Inn = "1234567890", Name = "Шерлок Холмс", PhoneNumber = "+4402072243688" }
                    );
                });

            modelBuilder.Entity("dotnet_web.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasData(
                        new { Id = 1, ClientId = 1, CreatedOn = new DateTime(2022, 3, 30, 17, 53, 0, 0, DateTimeKind.Unspecified), Name = "Драконьи шкуры", Status = 2 },
                        new { Id = 2, ClientId = 1, CreatedOn = new DateTime(2022, 3, 31, 10, 0, 0, 0, DateTimeKind.Unspecified), Name = "Автозапчасти", Status = 1 },
                        new { Id = 3, ClientId = 2, CreatedOn = new DateTime(2021, 2, 1, 10, 5, 34, 0, DateTimeKind.Unspecified), Name = "8\" Inch Floppy Disks", Status = 0 },
                        new { Id = 4, ClientId = 2, CreatedOn = new DateTime(2019, 12, 31, 18, 30, 0, 0, DateTimeKind.Unspecified), Name = "Bell Labs Technical Reports 1970-1974", Status = 0 }
                    );
                });

            modelBuilder.Entity("dotnet_web.Models.Order", b =>
                {
                    b.HasOne("dotnet_web.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
